server:
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: observability-core-backend
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    url: jdbc:postgresql://localhost:5432/observability_db
    username: docker_user
    password: docker_user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

app:
  jwt:
    secret: " вашему вниманию была представлена работа на тему программный комплекс "
    # Token validity in milliseconds (e.g., 24 hours)
    expiration-ms: 86400000
  cors:
    # This value can be overridden by the APP_CORS_ALLOWED_ORIGINS environment variable.
    # It supports multiple origins, separated by commas.
    allowed-origins: http://localhost:3000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.auzienko: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.type.descriptor.sql: TRACE