name: Build and Push Service to GHCR

on:
  push:
    branches: [ "main" ]

env:
  SERVICE_NAME: observability-core-backend
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up QEMU for multi-arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Buildx is a Docker CLI plugin that enables multi-arch builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ env.SERVICE_NAME }}
        uses: docker/build-push-action@v4
        with:
          context: ./${{ env.SERVICE_NAME }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.SERVICE_NAME }}:latest
          platforms: linux/amd64,linux/arm64